nodeLinker: node-modules

packageExtensions:
  "@firebase/analytics@*":
    dependencies:
      "@firebase/app": "*"
  "@firebase/app-check@*":
    dependencies:
      "@firebase/app": "*"
  "@firebase/auth-types@*":
    dependencies:
      "@firebase/app-types": "*"
  "@firebase/auth@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@firebase/firestore-types@*":
    dependencies:
      "@firebase/app-types": "*"
  "@firebase/firestore@*":
    dependencies:
      "@firebase/app": "*"
  "@firebase/functions@*":
    dependencies:
      "@firebase/app": "*"
  "@firebase/installations-types@*":
    dependencies:
      "@firebase/app-types": "*"
  "@firebase/installations@*":
    dependencies:
      "@firebase/app": "*"
  "@firebase/messaging@*":
    dependencies:
      "@firebase/app": "*"
  "@firebase/performance@*":
    dependencies:
      "@firebase/app": "*"
  "@firebase/remote-config@*":
    dependencies:
      "@firebase/app": "*"
  "@firebase/storage-types@*":
    dependencies:
      "@firebase/app-types": "*"
  "@firebase/storage@*":
    dependencies:
      "@firebase/app": "*"
  eslint-plugin-flowtype@*:
    peerDependenciesMeta:
      "@babel/plugin-syntax-flow":
        optional: true
      "@babel/plugin-transform-react-jsx":
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
