// Clams Table Data
export const clamsTableData = [
  {
    key: '1',
    clamName: 'Example Clam Name',
    clamColor: 'White',
    longitude: '0',
    latitude: '0',
    length: 0,
    width: 0,
    weight: 0,
    photoFile: 'Photo File',
    comments: 'Example Comment',
  },
  {
    key: '2',
    clamName: 'Example Clam Name',
    clamColor: 'White',
    longitude: '0',
    latitude: '0',
    length: 0,
    width: 0,
    weight: 0,
    photoFile: 'Photo File',
    comments: 'Example Comment',
  },
  {
    key: '3',
    clamName: 'Example Clam Name',
    clamColor: 'White',
    longitude: '0',
    latitude: '0',
    length: 0,
    width: 0,
    weight: 0,
    photoFile: 'Photo File',
    comments: 'Example Comment',
  },
  {
    key: '4',
    clamName: 'Example Clam Name',
    clamColor: 'White',
    longitude: '0',
    latitude: '0',
    length: 0,
    width: 0,
    weight: 0,
    photoFile: 'Photo File',
    comments: 'Example Comment',
  },
  {
    key: '5',
    clamName: 'Example Clam Name',
    clamColor: 'White',
    longitude: '0',
    latitude: '0',
    length: 0,
    width: 0,
    weight: 0,
    photoFile: 'Photo File',
    comments: 'Example Comment',
  },
  {
    key: '6',
    clamName: 'Example Clam Name',
    clamColor: 'White',
    longitude: '0',
    latitude: '0',
    length: 0,
    width: 0,
    weight: 0,
    photoFile: 'Photo File',
    comments: 'Example Comment',
  },
  {
    key: '7',
    clamName: 'Example Clam Name',
    clamColor: 'White',
    longitude: '0',
    latitude: '0',
    length: 0,
    width: 0,
    weight: 0,
    photoFile: 'Photo File',
    comments: 'Example Comment',
  },
  {
    key: '8',
    clamName: 'Example Clam Name',
    clamColor: 'White',
    longitude: '0',
    latitude: '0',
    length: 0,
    width: 0,
    weight: 0,
    photoFile: 'Photo File',
    comments: 'Example Comment',
  },
  {
    key: '9',
    clamName: 'Example Clam Name',
    clamColor: 'White',
    longitude: '0',
    latitude: '0',
    length: 0,
    width: 0,
    weight: 0,
    photoFile: 'Photo File',
    comments: 'Example Comment',
  },
  {
    key: '10',
    clamName: 'Example Clam Name',
    clamColor: 'White',
    longitude: '0',
    latitude: '0',
    length: 0,
    width: 0,
    weight: 0,
    photoFile: 'Photo File',
    comments: 'Example Comment',
  },
  {
    key: '11',
    clamName: 'Example Clam Name',
    clamColor: 'White',
    longitude: '0',
    latitude: '0',
    length: 0,
    width: 0,
    weight: 0,
    photoFile: 'Photo File',
    comments: 'Example Comment',
  },
];

export const clamsTableCols = [
  {
    title: 'Clam Name',
    dataIndex: 'clamName',
  },
  {
    title: 'Clam Color',
    dataIndex: 'clamColor',
  },
  {
    title: 'Longitude',
    dataIndex: 'longitude',
  },
  {
    title: 'Latitude',
    dataIndex: 'latitude',
  },
  {
    title: 'Length',
    dataIndex: 'length',
  },
  {
    title: 'Width',
    dataIndex: 'width',
  },
  {
    title: 'Weight',
    dataIndex: 'weight',
  },
  {
    title: 'Photo File',
    dataIndex: 'photoFile',
  },
  {
    title: 'Comments',
    dataIndex: 'comments',
  },
];

// Raker Table Data
export const rakerTableData = [
  {
    key: '1',
    rakerName: 'text',
    timeStart: 'text',
    timeEnd: 'text',
    startLat: 'text',
    startLong: 'text',
    midLat: 'text',
    midLong: 'text',
    endLat: 'text',
    endLong: 'text',
    startDepth: 'text',
    endDepth: 'text',
    distanceRaked: 'text',
    rakeWidth: 'text',
  },
  {
    key: '2',
    rakerName: 'text',
    timeStart: 'text',
    timeEnd: 'text',
    startLat: 'text',
    startLong: 'text',
    midLat: 'text',
    midLong: 'text',
    endLat: 'text',
    endLong: 'text',
    startDepth: 'text',
    endDepth: 'text',
    distanceRaked: 'text',
    rakeWidth: 'text',
  },
  {
    key: '3',
    rakerName: 'text',
    timeStart: 'text',
    timeEnd: 'text',
    startLat: 'text',
    startLong: 'text',
    midLat: 'text',
    midLong: 'text',
    endLat: 'text',
    endLong: 'text',
    startDepth: 'text',
    endDepth: 'text',
    distanceRaked: 'text',
    rakeWidth: 'text',
  },
  {
    key: '4',
    rakerName: 'text',
    timeStart: 'text',
    timeEnd: 'text',
    startLat: 'text',
    startLong: 'text',
    midLat: 'text',
    midLong: 'text',
    endLat: 'text',
    endLong: 'text',
    startDepth: 'text',
    endDepth: 'text',
    distanceRaked: 'text',
    rakeWidth: 'text',
  },
  {
    key: '5',
    rakerName: 'text',
    timeStart: 'text',
    timeEnd: 'text',
    startLat: 'text',
    startLong: 'text',
    midLat: 'text',
    midLong: 'text',
    endLat: 'text',
    endLong: 'text',
    startDepth: 'text',
    endDepth: 'text',
    distanceRaked: 'text',
    rakeWidth: 'text',
  },
  {
    key: '6',
    rakerName: 'text',
    timeStart: 'text',
    timeEnd: 'text',
    startLat: 'text',
    startLong: 'text',
    midLat: 'text',
    midLong: 'text',
    endLat: 'text',
    endLong: 'text',
    startDepth: 'text',
    endDepth: 'text',
    distanceRaked: 'text',
    rakeWidth: 'text',
  },
];

export const rakerTableCols = [
  {
    title: 'Raker Name',
    dataIndex: 'rakerName',
  },
  {
    title: 'Time Start',
    dataIndex: 'timeStart',
  },
  {
    title: 'Time End',
    dataIndex: 'timeEnd',
  },
  {
    title: 'Start Lat',
    dataIndex: 'startLat',
  },
  {
    title: 'Start Long',
    dataIndex: 'startLong',
  },
  {
    title: 'Mid Lat',
    dataIndex: 'midLat',
  },
  {
    title: 'Mid Long',
    dataIndex: 'midLong',
  },
  {
    title: 'End Lat',
    dataIndex: 'endLat',
  },
  {
    title: 'End Long',
    dataIndex: 'endLong',
  },
  {
    title: 'Start Depth',
    dataIndex: 'startDepth',
  },
  {
    title: 'End Depth',
    dataIndex: 'endDepth',
  },
  {
    title: 'Distance Raked',
    dataIndex: 'distanceRaked',
  },
  {
    title: 'Rake Width',
    dataIndex: 'rakeWidth',
  },
];
